#!/bin/bash

wget https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -x packages-microsoft-prod.deb ./
rm packages-microsoft-prod.deb
apt-get update -y
apt-get install -y dotnet-sdk-7.0
dotnet tool install -g Microsoft.dotnet-interactive
PATH="${PATH}:${HOME}/.dotnet/tools"
dotnet interactive jupyter install
